name: NewPlayerPerks
version: '${version}'
main: com.github.lukesky19.newPlayerPerks.NewPlayerPerks
api-version: '1.21'
depend: [SkyLib, LuckPerms]
softdepend: [BentoBox-VoidTeleport, Essentials, BentoBox-IslandFly]

permissions:
    newplayerperks.commands.newplayerperks:
        description: Base Command Permission
        default: op
    newplayerperks.commands.newplayerperks.reload:
        description: Permission to reload the plugin.
        default: op
    newplayerperks.commands.newplayerperks.add:
        description: Permission to give player perks.
        default: op
    newplayerperks.commands.newplayerperks.remove:
        description: Permission to remove player perks.
        default: op
    newplayerperks.commands.newplayerperks.enable:
        description: Permission to let a player enable their perks.
        default: op
    newplayerperks.commands.newplayerperks.disable:
        description: Permission to let a player disable their perks.
        default: op
    newplayerperks.commands.newplayerperks.help:
        description: Permission to view the plugin's help message.
        default: op