config-version: 1.0.0.0
locale: en_US
invulnerable: true
# Requires Essentials
essentials-fly: false
# Requires the BentoBox IslandFly addon
island-fly: false
keep-inventory: true
keep-exp: true
# Requires BentoBox VoidTeleport addon
void-teleport: true
period: 6h